### PR TITLE
lib50 2.1, Windows support

### PR DESCRIPTION
**Pull request by Jelleas**

### CODE REVIEW

**Comment by dmalan** [comment]
@Jelleas I didn't realize this was still pending, and I added `readline` back into `develop` (which had drifted from `master`). Are these good to be merged all together?

**Comment by Jelleas** [comment]
No this PR is stale and albeit undocumented is directly connected to another PR @ https://github.com/cs50/lib50/pull/35.  That also grew stale and got closed last year.

I still believe it's ultimately worth the effort to try and get submit50/check50 to run under Windows at some point. But right now a lot of the underlying difficulties are tied to git and its need for a pseudoterminal for which there is seemingly little support under Windows. Given that git(Hub) might proof tricky to use soon, with the change to passwords, I'm not sure if it's worth the time/effort now.

**Comment by dmalan** [comment]
Hm, so this PR was from `develop`. Should we move the latest `master` on top of `develop` so that they're back in sync then, then I'll re-add `readline`?

**Comment by Jelleas** [comment]
Ah, that explains. So beyond the Windows support part there are some commits in develop related to a custom honesty prompt. That happen to also be linked to a lib50 PR (https://github.com/cs50/lib50/pull/60). That should go through, but I personally won't have time to fix it this week or the next.

So for now, do move `master` back on top of `develop`, and in the future we should stop merging commits into develop if they're depending on a PR elsewhere 😅

**Comment by dmalan** [comment]
Okay, added back just `readline` for now if you want to re-PR with the requisite commits for `lib50` when ready!

https://github.com/cs50/submit50/pull/250

**Pull request closed without merging**
